apiVersion: v1
kind: Pod
metadata:
  name: api-client
spec:
  containers:
  - name: client
    image: alpine
    command: ["sh", "-c", "echo La API Key es $MY_API_KEY && sleep 3600"]
    env:
    - name: MY_API_KEY
      valueFrom:
        secretKeyRef:
          name: api-fintech
          key: API_KEY
