apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gitops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mi-web
  template:
    metadata:
      labels:
        app: mi-web
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: mi-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
